name: Build and Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract version from Cargo.toml
        run: |
          VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build and package
        run: cargo build --release
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: target/release/maison
          token: ${{ secrets.RELEASE_TOKEN }}
